---
extends: airbnb-base

parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

env:
  es6: true
  node: true

globals:
  document: false
  navigator: false
  window: false

rules:
  arrow-parens:
    - 2
    - as-needed
  class-methods-use-this: 0
  comma-dangle:
    - 2
    - never
  func-names: 0
  max-len:
    - error
    - 120
    - 2
    - ignoreUrls: true
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  no-underscore-dangle: 0
  no-useless-escape: 0
  padded-blocks:
    - 2
    - blocks: never
      classes: never
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
  import/no-extraneous-dependencies: 0
